title: WhosThatPet.io
description: KI-gestützte Haustier-Matching-Plattform
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://whosthatpet.io" # replace with your actual domain

# Build settings
theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag

# Navigation
navigation:
  - title: Home
    url: /
  - title: Nutzerrollen
    url: /roles
  - title: Funktionsweise
    url: /flows
  - title: Technische Details
    url: /technical
  - title: Datenschutz
    url: /privacy
